- name: Download repo puppet
  get_url:
   url: https://apt.puppetlabs.com/puppet5-release-xenial.deb
   dest: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: instalar repositorio
  apt:
   deb: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: install puppetagent repo
  yum:
   name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
   state: present
  when: ansible_os_family == "RedHat"
   
